### ISSUE TITLE
Instruction Access Fault when running xv6 on VulpineSystem

### ISSUE THREAD

**Issue by TalonFloof** [VulpineSystem/vulpinesystem#1]
After successfully compiling both VulpineSystem and the version of xv6 for Vulpine, running the xv6 kernel immediately crashes the emulator. The following message is shown on the console:
```
fatal exception while fetching instruction!
```
---
I decided to look deeper into the problem, I added a line of code that prints out the exception ID before it shows the fatal exception message. I then got the following message on the console:
```
Exception: 1
fatal exception while fetching instruction!
```

Looking at semu.h, Exception 1 is an INSTRUCTION_ACCESS_FAULT. This shows that the address bus wasn't able to access the memory where the instruction lied for some reason.

---
Afterwards, I then looked at how far the emulator was running before it crashed. I did this by uncommenting line 134 in main.c. The output then changed to this:
```
80000000: 29117
80000004: A8010113
80000008: 25F36505
Exception: 1
fatal exception while fetching instruction!
```
---

Taking a look at the generated kernel.asm file from xv6, these are the lines of assembly code it's running:
```
0000000080000000 <_entry>:
    80000000:	00029117          	auipc	sp,0x29
    80000004:	a8010113          	addi	sp,sp,-1408 # 80028a80 <stack0>
    80000008:	6505                lui	a0,0x1
    8000000a:	f14025f3          	csrr	a1,mhartid <-- Crashes while fetching this!
    8000000e:	0585                addi	a1,a1,1
    80000010:	02b50533          	mul	a0,a0,a1
    80000014:	912a                add	sp,sp,a0
    80000016:	076000ef          	jal	ra,8000008c <start>
```
---

I'm not sure if this issue is occurring simply because VulpineSystem is new and isn't finished yet, or if I did something wrong while compiling xv6. Any help on this issue is appreciated!

**Comment by ry755** [comment]
Ohhhh, yes I know what the issue is, I ran into it myself when I was first getting started. I forgot to mention this in the readme, but VulpineSystem doesn't support RISC-V's `C` extension, meaning it doesn't support compressed instructions. As shown in the kernel.asm file, some instructions are 2 bytes, while others are 4 bytes. VulpineSystem doesn't like that :P

The only way to fix this is by rebuilding the gcc toolchain. Follow the "Installation (Newlib)" instructions [here](https://github.com/riscv-collab/riscv-gnu-toolchain), but when running the `./configure` command, add `--with-arch=rv64g`. I also recommend running `make` with `-j12` (replace 12 with how many threads your CPU has) in order to speed up the build process.

After that, just rebuild xv6 and everything should work :3

**Comment by TalonFloof** [comment]
I didn't even think about the RISC-V Compressed Instructions! That makes a lot of sense now. I followed your instructions and rebuilt the gcc toolchain and then rebuilt xv6. It now runs with no issues. Thank your for your help. :3 

Now I can finally do this!
![Screenshot from 2022-12-02 19-04-13](https://user-images.githubusercontent.com/105325988/205414927-d7e0d6a0-a3ae-4a82-98fc-d76ba782a0a8.png)
I've been waiting to do that for some reason...

**Comment by ry755** [comment]
hehe nice I'm glad it works now :3
I'll add a note about the compressed instructions to the readme.
